# Generated by Django 6.0.3 on 2026-04-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default.png', upload_to='products'),
        ),
    ]
